apiVersion: v1
kind: PersistentVolume
metadata:
  name: software-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"   # Path on the minikube node
