apiVersion: v1
kind: Service
metadata:
  name: software-service
spec:
  selector:
    app: software
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
